LisaMillet/artup

app/models/answer.rb, app/models/journey.rb, app/models/journey_piece.rb, app/models/piece.rb, app/models/question.rb, app/models/user.rb, app/models/user_answer.rb, app/models/user_journey.rb, db/migrate/20230306161316_create_users.rb, db/migrate/20230306161758_create_journeys.rb, db/migrate/20230306162933_create_pieces.rb, db/migrate/20230306163347_create_questions.rb, db/migrate/20230306163526_create_answers.rb, db/migrate/20230306163915_create_journey_pieces.rb, db/migrate/20230306164002_create_user_journeys.rb, db/migrate/20230306164044_create_user_answers.rb, db/migrate/20230306170138_change_column_right_answer_to_boolean.rb, db/schema.rb, test/models/answer_test.rb, test/models/journey_piece_test.rb, test/models/journey_test.rb, test/models/piece_test.rb, test/models/question_test.rb, test/models/user_answer_test.rb, test/models/user_journey_test.rb, test/models/user_test.rb
- Created all models from DB Schemas
- Created all dependencies
=> added models and dependencies

app/controllers/questions_controller.rb, config/routes.rb
- Created resources for Questions
- Created Show action in QuestionsController
=> added questions resources and show action

app/controllers/answers_controller.rb, app/controllers/questions_controller.rb, app/views/questions/show.html.erb
- Created Questions -> show.html.erb
- Created HTML to display "All questions"
- Added action "show" in QuestionsController
=> added questions show

app/controllers/answers_controller.rb, app/controllers/application_controller.rb, app/controllers/questions_controller.rb, app/controllers/user_journey_answers_controller.rb, app/models/answer.rb, app/models/user.rb, app/models/user_journey.rb, app/models/user_journey_answer.rb, app/views/questions/show.html.erb, app/views/user_journeys/show.html.erb, config/routes.rb, db/migrate/20230307140401_change_user_answers_to_user_journey_answers.rb, db/schema.rb, db/seeds.rb, test/controllers/user_journey_answers_controller_test.rb
- Added user_journey_answers
- Changed user_answers to be user_journey_answers everywhere (seed, schema, controllers, models)
=> Questions answers controllers

app/controllers/questions_controller.rb, app/controllers/user_journey_answers_controller.rb, app/policies/question_policy.rb, app/policies/user_journey_answer_policy.rb
- Created questions_policy and user_journey_answer_policy files
- Added Pundit authorizations for questions controller and user_journey_answers controller
=> Added Authorizations for questions and user_journey_answers

Gemfile.lock, db/seeds.rb
=> Mercredi muriel

app/assets/stylesheets/components/_background.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/views/layouts/application.html.erb
- Fixed the position of the top navbar (but it's broken, needs a ticket)
- Changed all color variables to match our color palette
=> changed color variables and fixed the navbar

app/views/layouts/application.html.erb
- Added padding-top to the entire body so it's always below the top navbar
=> fixed the top navbar

app/views/layouts/application.html.erb, app/views/questions/show.html.erb, app/views/shared/_navbar_fixed_bottom.html.erb
- Fixed container width to 100%
=> fixed container width

app/assets/stylesheets/pages/_questions_show.scss, app/controllers/user_journey_answers_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/question_controller.js, app/views/questions/_answered_show.html.erb, app/views/questions/show.html.erb, db/seeds.rb
- Added Green and Red answers through a partial and Stimulus controllers
=> added red and green answers

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_navbar_fixed_bottom.scss, app/assets/stylesheets/components/_score.scss, app/views/user_journeys/show.html.erb
- Made multiple small changes for better CSS
=> multiple small changes for better CSS

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_user_journey_show.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
- Added "Visitez le musée autrement" to the navbar in the User Journey Show
- Removed it from the page and made the "Testez vos connaissances" a H1 instead
- Changed the User Journey icon from directions to steps
=> changed navbar for the user journey show

app/assets/stylesheets/pages/_questions_show.scss, app/views/questions/_answered_show.html.erb, app/views/user_journey_pieces/_show_with_media.html.erb, app/views/user_journeys/show.html.erb
=> made some CSS changes

app/assets/stylesheets/pages/_questions_show.scss
- Changed Questions' Form's padding and margin for better clarity
- Added a box-shadow after Diane's feedback
- Changed Right answer's green background and color
- Changed Wrong answer's red background and color
=> changed questions' CSS for better clarity

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_questions_show.scss, app/views/journeys/show.html.erb
CHANGES AFTER DEMO FEEDBACKS :
- Changed the position of the "continuer" button so you never have to scroll
- Changed the font so it's "sans-serif" and clearer
- Changed the top "visitez le musée autrement" but it's still not good
=> added changes after demo feedback

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_user_journey_show.scss, app/views/user_journey_pieces/_show_with_media.html.erb
- Fixed photo's width so it fits the screen and doesn't create horizontal scrolling
=> fixed user journey pieces show

app/views/user_journeys/show.html.erb
- piece.location ajouté sur les card locked & unlocked
=> adding piece.location on user_journey cards

app/assets/stylesheets/components/_score.scss, app/assets/stylesheets/pages/_questions_show.scss, app/views/journeys/show.html.erb
- Changed score color from $green to $dark-green so it's visible for the demo
=> Green red answers

app/views/user_journey_pieces/_show_with_media.html.erb
- Changed image width for the User Journey Show so it fits the screen (390 instead of 400)
=> changed image width

app/controllers/user_journey_answers_controller.rb, app/models/user_journey.rb, app/models/user_journey_piece.rb, app/views/user_journeys/_user_journey_live.html.erb, app/views/user_journeys/_user_journey_quit.html.erb, app/views/user_journeys/show.html.erb
résolution pb de redirection après la dernière oeuvre
=> résolution pb de redirection après la dernière oeuvre

app/javascript/controllers/scanner_controller.js, app/views/questions/_answer_label.html.erb, app/views/questions/show.html.erb, app/views/user_journey_pieces/_show_with_media.html.erb, app/views/user_journey_pieces/show.html.erb
=> Jeudi2muriel
